#!/bin/sh
set -ueo pipefail
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.md" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./scripts/update-toc

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
